### ISSUE TITLE
ava.lang.UnsatisfiedLinkError: No implementation found for void com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init() 

### ISSUE THREAD

**Issue by pranimation** [TorrentStream/TorrentStream-Android#80]
Error Stack:
No implementation found for void com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init() (tried Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_swig_1module_1init and Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_swig_1module_1init__)
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init(Native Method)
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:3331)
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_error_notification_get(Native Method)
        at com.frostwire.jlibtorrent.swig.alert.<clinit>(alert.java:494)
        at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(AlertType.java:11)
        at com.frostwire.jlibtorrent.SessionManager.<clinit>(SessionManager.java:23)
        at com.github.se_bastiaan.torrentstream.TorrentStream$3.run(TorrentStream.java:132)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        
  **Phone**: Panasonic Eluga Ray x
 Os: AOSP 6.0
 
 Tried Progurad Rule from [Issue](https://github.com/TorrentStream/TorrentStream-Android/issues/51) but no effect

**Comment by se-bastiaan** [comment]
You are not asking a question.
